schema: 1
story: "2.1"
story_title: "3D 컨피규레이터 기반 구조 구축"
gate: "CONCERNS"
status_reason: "Dev(Mock) 환경에서 로그인 후 /configurator 접근 시 재로그인 루프 발생: mock-token을 Supabase 실제 토큰으로 검증하여 인증 실패. 프로덕션 실 Supabase에서는 비재현 예상. Mock 분기 보강 필요."
reviewer: "Quinn (Test Architect)"
updated: "2025-10-15T00:00:00Z"
waiver: { active: false }
top_issues:
  - id: "AUTH-MOCK-TOKEN-MISMATCH"
    severity: high
    finding: "Mock 토큰(mock-token-*)을 미들웨어/API 인증이 Supabase로 검증하여 항상 실패"
    suggested_action: "isMockMode() 분기에서 mockGetUser(token)로 검증하도록 미들웨어/인증 유틸 보강"
  - id: "CFG-BFF-401"
    severity: medium
    finding: "/api/v1/bff/configurator 가 인증 실패 시 401 → 초기 로드 차단"
    suggested_action: "Mock 인증 컨텍스트 제공 또는 로딩/오류 UX 세분화"
risk_summary:
  totals: { critical: 0, high: 1, medium: 1, low: 0 }
  recommendations:
    must_fix:
      - "auth-middleware.ts / api/auth.ts에 Mock 토큰 처리 분기 추가"
    monitor:
      - "패치 후 E2E: 로그인(Mock) → /configurator → BFF 200 확인"
